const data = {
    products:[
        {
          "title": "Samsung Galaxy A03 Core Smartphone",
          "slug": "Samsung-Galaxy-A03-Core-Smartphone",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 2300,
          "stock": 15000,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/mobile/samsung/galaxy-a03-core/a03-core-002-228x228.webp",
          "category": "65205289e9fa4d75f4347890",
          },
        {
          "title": "Vivo Y36 Smartphone",
          "slug": "Vivo-Y36-Smartphone",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 21000,
          "stock": 234,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/mobile/vivo/y36/y36-gold-228x228.webp",
          "category": "65205289e9fa4d75f4347890",
          },
        {
          "title": "Samsung Galaxy F13",
          "slug": "Samsung-Galaxy-F13",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 2300,
          "stock": 234,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/mobile/samsung/galaxy-f13/galaxy-f13-001-228x228.webp",
          "category": "65205289e9fa4d75f4347890",
          },
        {
          "title": "ROWA 32S52 32 Inch",
          "slug": "ROWA-32S52-32-Inch",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 23000,
          "stock": 234,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/television/rowa/32s52/32s52-01-500x500.webp",
          "category": "6520525ee9fa4d75f4347889",
          },
        {
          "title": "JVCO J9TS 32 Inch",
          "slug": "JVCO-J9TS-32-Inch",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 25000,
          "stock": 234,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/television/jvco/j9ts/j9ts-01-500x500.webp",
          "category": "6520525ee9fa4d75f4347889",
          },
        {
          "title": "OnePlus 32 Y1 Y Series 32-Inch",
          "slug": "OnePlus-32-Y1-Y-Series-32-Inch",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 28000,
          "stock": 234,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/television/oneplus/Y1G-1-500x500.webp",
          "category": "65205243e9fa4d75f4347882",
          },
        {
          "title": "Apple iPad 10.9-Inch",
          "slug": "Apple-iPad-10.9-Inch",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 28000,
          "stock": 234,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/tablet-pc/apple/ipad-9th-gen/ipad-silver-wifi-228x228.webp",
          "category": "65205243e9fa4d75f4347882",
          },
        {
          "title": "Apple iPad Air",
          "slug": "Apple-iPad-Air",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 28000,
          "stock": 234,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/tablet/apple/ipad-air-5th-gen/ipad-air-space-gray-01-228x228.jpg",
          "category": "65205243e9fa4d75f4347882",
          },
        {
          "title": "Toshiba Dynabook",
          "slug": "Toshiba-Dynabook",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 28000,
          "stock": 234,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/laptop/toshiba/satellite-pro-c40-g-109/satellite-pro-c40-g-109-01-228x228.webp",
          "category": "6520521ee9fa4d75f434787b",
          },
        {
          "title": "Asus P1511CMA",
          "slug": "Asus-P1511CMA ",
          "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sunt, blanditiis veniam dolorem at quia quae voluptatum minima labore praesentium necessitatibus consequuntur enim quasi nulla iure autem magnam earum numquam? Id rem distinctio possimus pariatur reiciendis nemo iure amet soluta qui eum dignissimos alias, deserunt molestiae, adipisci consequuntur voluptates incidunt aspernatur harum deleniti doloribus.",
          "price": 28000,
          "stock": 234,
          "sold": 21,
          "shipping": 0,
          "image": "https://www.startech.com.bd/image/cache/catalog/laptop/asus/p1511cma/p1511cma-slate-grey-01-228x228.webp",
          "category": "\"6520521ee9fa4d75f434787b\"",
          }
      ]
      
};

module.exports = data;